version: '3.0'
services:
  mysqldb:
    container_name: mysqldb
    image: mysql:8.0
    restart: always
    command: --lower_case_table_names=1
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: root
    volumes:
      - ./mysql-volume:/var/lib/mysql
      - ./src/main/resources/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "3306:3306"
    networks:
      struts2-mysql-net:

  struts2-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: struts2-app-container
    ports:
        - "80:8080"
    restart: on-failure
    depends_on:
      - mysqldb
    environment:
      DATABASE_HOST: mysqldb
      DATABASE_PORT: 3306
      DATABASE_NAME: mst
      DATABASE_USER: root
      DATABASE_PASSWORD: root
    networks:
      struts2-mysql-net:

networks:
  struts2-mysql-net:
